apiVersion: shoot-fleet-agent-service.extensions.config.gardener.cloud/v1alpha1
kind: FleetAgentConfig
defaultConfig:
  kubeconfig: #base64 encoded kubeconfig of fleet cluster
  namespace: clusters #namespace to register clusters in fleet manager cluster
  labels:
    allshootswillhavethislabel: somevalue
# example of project specific config:
#projectConfig:
#  projectABC:
#    kubeconfig: #base64 encoded kubeconfig of ABC fleet cluster
#    namespace: nsABC #namespace to register clusters in fleet manager cluster
#    labels:
#      myProjectABClabel1: myvalue
#      myProjectABClabel2: myvalue2
#  projectDEF:
#    kubeconfig: #base64 encoded kubeconfig of DEF fleet cluster
#    namespace: nsDEF #namespace to register clusters in fleet manager cluster
#    labels:
#      myProjectDEFlabel1: myvalue
#      myProjectDEFlabel2: myvalue2
  