---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener-extension-shoot-fleet-agent
  labels:
    app.kubernetes.io/name: gardener-extension-shoot-fleet-agent
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - gardener-extension-shoot-fleet-agent
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
