---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: certificate-service
  namespace: shoot--foo--bar
spec:
  type: shoot-fleet-agent
  providerConfig:
    apiVersion: shoot-fleet-agent-service.extensions.config.gardener.cloud/v1alpha1
    kind: FleetAgentConfig
    clientConnection:
      kubeconfig: #base64 encoded kubeconfig of fleet cluster
    namespace: clusters #namespace to register clusters in fleet manager cluster
