---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: certificate-service
  namespace: shoot--foo--bar
spec:
  type: shoot-fleet-agent
  providerConfig:
    apiVersion: service.cert.extensions.gardener.cloud/v1alpha1
    kind: CertConfig
