---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extensions.gardener.cloud:extension-shoot-fleet-agent
  labels:
    app.kubernetes.io/name: gardener-extension-shoot-fleet-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "*"
