---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-extension-shoot-fleet-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-shoot-fleet-agent
    helm.sh/chart: gardener-extension-shoot-fleet-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
